name: fbloc_cli
description: A scaffolding CLI for Flutter projects with feature-first architecture and BLoC/Cubit state management.
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.4
  interact: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0

repository: https://github.com/abhaysaqi/fbloc_cli
issue_tracker: https://github.com/abhaysaqi/fbloc_cli/issues

topics:
  - cli
  - scaffolding
  - bloc
  - flutter
  - generator

executables:
  fbloc: fbloc_cli
